# Assemble reel.js from its parts: python3 build.py
h = open('_helpers.js').read().replace("const CH = [[0, 7.2], [7.2, 16.8], [16.8, 50.4], [50.4, 60]];", "let CH = [];")
seek = open('_seek.js').read()
head = "/* Cassie — explainer reel with voiceover (all features). 1080×1920, length set by the narration (timeline.js).\n   Generated by build.py from _helpers.js, _collage.js, _art.js, _scenes.js, _chrome.js, _seek.js. */\n(function () {\n  'use strict';\n"
open('reel.js', 'w').write(''.join([head, h, open('_collage.js').read(), open('_art.js').read(), open('_scenes.js').read(), open('_chrome.js').read(), seek]))
print('wrote reel.js')
