/* Cassie — explainer reel with voiceover (all features). 1080×1920, length set by the narration (timeline.js).
   Generated by build.py from _helpers.js, _collage.js, _art.js, _scenes.js, _chrome.js, _seek.js. */
(function () {
  'use strict';
  const BAR = 2.4;
  const $ = (s, r = document) => r.querySelector(s);
  const clamp = (v, a = 0, b = 1) => Math.min(b, Math.max(a, v));
  const span = (t, a, b) => clamp((t - a) / (b - a));
  const ease = (k) => { k = clamp(k); return k * k * (3 - 2 * k); };
  const out3 = (k) => 1 - Math.pow(1 - clamp(k), 3);
  const back = (k) => { k = clamp(k); const c = 1.70158; return 1 + (c + 1) * Math.pow(k - 1, 3) + c * Math.pow(k - 1, 2); };
  const lerp = (a, b, k) => a + (b - a) * k;
  const content = $('#content'), topL = $('#top');
  const make = (html, parent) => { const d = document.createElement('div'); d.innerHTML = html.trim(); const n = d.firstChild; parent.appendChild(n); return n; };
  const CUR = (w = 34, fill = '#fff') => `<svg viewBox="100 80 305 350" width="${w}" height="${w * 1.15}" style="position:absolute;filter:drop-shadow(0 4px 6px rgba(0,0,0,.35))"><path d="M108 90 L395 259 L275 281 L342 399 L287 422 L225 300 L108 382 Z" fill="${fill}" stroke="#0b0a0f" stroke-width="22" stroke-linejoin="round" paint-order="stroke"/></svg>`;
  // world coords for the 3D stage inside the 1000×600 card
  const W = (px, py) => [(px - 500) / 124.5, 0.35 - (py - 300) / 124.5];

  /* ---------------- chapters ---------------- */
  let CH = [];

  /* ---------------- colours per scene (felt palette) ---------------- */
  const PAL = {
    intro: ['#f2a7b5', '#b9a6ff', '#ffd1c2'], problem: ['#a98bff', '#f08ab0', '#6b5cff'],
    red: ['#e8545c', '#f2a7b5', '#ffc7a8'], maroon: ['#8a3a46', '#c9a04a', '#f2a7b5'], navy: ['#3b5bdb', '#7fb3ff', '#b9a6ff'],
    pink: ['#ee9a8c', '#f7b9c8', '#ffd6c9'], grey: ['#8e96a6', '#c9cfdb', '#f2a7b5'], green: ['#4fbf8a', '#a6e3c4', '#b9a6ff'],
  };

  /* ---------------- scene helpers ---------------- */
  function kin(root, words, acc = []) {
    const box = make(`<div class="kin"></div>`, root);
    words.forEach((w, i) => make(`<span class="w ${acc.includes(i) ? 'acc' : ''}">${w}</span>`, box));
    return box;
  }
  function kinUpdate(box, lt, start = 0.1, gap = 0.22) {
    [...box.children].forEach((w, i) => {
      const k = span(lt, start + i * gap, start + i * gap + 0.38);
      w.style.opacity = k; w.style.filter = `blur(${(1 - k) * 14}px)`; w.style.transform = `translateY(${(1 - out3(k)) * 26}px)`;
    });
  }
  const ICONS = {
    book: '<path d="M4 5a2 2 0 0 1 2-2h13v16H6a2 2 0 0 0-2 2z" fill="#f6d1d6"/><path d="M4 5v16M8 7h8" stroke="#16131c" stroke-width="1.6" fill="none"/>',
    pencil: '<path d="M4 20l1-4L16 5l3 3L8 19z" fill="#ffd166" stroke="#16131c" stroke-width="1.4"/>',
    flask: '<path d="M9 3h6M10 3v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3" fill="#c9e7ff" stroke="#16131c" stroke-width="1.4"/>',
    bulb: '<circle cx="12" cy="10" r="6" fill="#ffe27a" stroke="#16131c" stroke-width="1.4"/><path d="M9 17h6M10 20h4" stroke="#16131c" stroke-width="1.6"/>',
    clock: '<circle cx="12" cy="12" r="9" fill="#fff" stroke="#16131c" stroke-width="1.6"/><path d="M12 7v5l3 2" stroke="#d8343c" stroke-width="1.8" fill="none" stroke-linecap="round"/>',
    calc: '<rect x="5" y="3" width="14" height="18" rx="2" fill="#e9e4ff" stroke="#16131c" stroke-width="1.4"/><path d="M8 7h8M8 12h2M12 12h2M8 16h2M12 16h2" stroke="#16131c" stroke-width="1.6"/>',
    lock: '<rect x="5" y="10" width="14" height="11" rx="2" fill="#16131c"/><path d="M8 10V7a4 4 0 0 1 8 0v3" stroke="#16131c" stroke-width="2" fill="none"/>',
  };
  const icon = (name, parent, size = 44) => make(`<svg class="ico" viewBox="0 0 24 24" width="${size}" height="${size}" style="width:${size}px;height:${size}px">${ICONS[name]}</svg>`, parent);
  function popIn(n, lt, at, dur = 0.35, extra = '') {
    const k = back(span(lt, at, at + dur));
    n.style.opacity = span(lt, at, at + 0.1); n.style.transform = `${extra} scale(${k})`;
  }
  function tag(n, label) { return make(`<div class="ftag"><b>${n}</b>${label}</div>`, topL); }

  function collageCards(r) {
    const C = [
      ['<div class="lbl">PDF · 412 pages</div><div style="height:8px;background:#eee;border-radius:4px;margin-top:10px"></div><div style="height:8px;background:#eee;border-radius:4px;margin-top:8px;width:70%"></div>', 150, 110, '#fff'],
      ['<div class="lbl" style="color:#fff">SLIDES</div><div style="height:46px;background:rgba(255,255,255,.25);border-radius:6px;margin-top:8px"></div>', 150, 100, '#5b4bd8'],
      ['<div style="font:700 15px Inter">“Explain the Krebs cycle??”</div>', 170, 70, '#fff3b0'],
      ['<svg viewBox="0 0 100 50" width="130" height="60"><path d="M5 45 L30 30 L50 35 L75 12 L95 8" stroke="#d8343c" stroke-width="4" fill="none"/></svg>', 150, 90, '#fff'],
      ['<div style="font:900 34px Inter;color:#16131c">23:59</div><div class="lbl">due tonight</div>', 140, 90, '#ffd6dc'],
      ['<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:5px">' + '<i style="height:18px;background:#ddd;border-radius:4px"></i>'.repeat(9) + '</div>', 120, 100, '#e9e4ff'],
      ['<div style="width:100%;height:56px;border-radius:8px;background:linear-gradient(135deg,#222,#555);display:grid;place-items:center;color:#fff;font:900 22px Inter">▶</div><div class="lbl" style="margin-top:6px">lecture 7 · 1:42:10</div>', 160, 100, '#fff'],
      ['<div style="font:800 15px Inter">Flashcard</div><div style="font:600 14px Inter;color:#6f6a76;margin-top:6px">mitochondria = ?</div>', 140, 80, '#fff'],
      ['<div style="font:800 26px Inter">∫ x² dx</div>', 120, 70, '#d9f2e6'],
      ['<div style="font:700 14px Inter">37 tabs open</div><div style="display:flex;gap:3px;margin-top:8px">' + '<i style="flex:1;height:10px;background:#c8c3d0;border-radius:3px"></i>'.repeat(6) + '</div>', 150, 64, '#fff'],
    ];
    return C.map(([html, w, h, bg]) => make(`<div class="card2" style="width:${w}px;height:${h}px;padding:12px;background:${bg}">${html}</div>`, r));
  }
  const ART = '<div style="padding:22px 26px;font:15px/1.6 Inter;color:#2a282e"><div style="font:800 11px Inter;letter-spacing:.14em;color:#999">BIONOTES</div><div style="font:800 26px Inter;color:#121116;margin:4px 0 10px">Cellular Respiration</div>Cells release the energy stored in glucose in stages. After glycolysis, the process moves into the mitochondria. <span class="mk" style="position:relative">The Krebs cycle turns acetyl-CoA into CO₂, NADH and FADH₂.<i style="position:absolute;inset:-1px -2px;background:#bcd8ff;border-radius:4px;z-index:-1;transform-origin:left"></i></span> Without oxygen, the whole process stalls.</div>';
  /* ---------------- scenes, timed from the voiceover (timeline.js) ---------------- */
  const TLK = {}; window.TL.forEach((s) => { TLK[s.key] = s; });
  const LEAD = 0.35;
  // roughly when a word is spoken inside its scene (by character position in the line)
  const said = (key, word) => { const s = TLK[key]; const i = s.text.toLowerCase().indexOf(word.toLowerCase()); return LEAD + s.voDur * Math.max(0, i) / s.text.length; };
  const scenes = [];
  let featNo = 0;
  function S(key, pal, build, label) {
    const tl = TLK[key]; if (!tl) throw new Error('no timeline for ' + key);
    const root = make(`<div class="scene"></div>`, content);
    const s = { key, t0: tl.t0, t1: tl.t0 + tl.dur, d: tl.dur, pal, root, tags: [] };
    if (label) { featNo += 1; s.tags.push(tag(String(featNo).padStart(2, '0'), label)); }
    Object.assign(s, build(root, s));
    scenes.push(s);
  }
  const chip = (txt, parent, dark = false, size = 20) => make(`<div style="position:absolute;font:800 ${size}px Inter;background:${dark ? '#16131c' : '#fff'};color:${dark ? '#fff' : '#16131c'};padding:9px 15px;border-radius:999px;box-shadow:0 8px 20px rgba(0,0,0,.08);white-space:nowrap">${txt}</div>`, parent);
  const typeInto = (n, html, k) => { const plain = html.replace(/<[^>]+>/g, ''), c = Math.floor(clamp(k) * plain.length); let shown = 0, out = ''; for (const part of html.split(/(<[^>]+>)/)) { if (part.startsWith('<')) out += part; else { out += part.slice(0, Math.max(0, c - shown)); shown += part.length; } } n.innerHTML = out; };
  const POPHTML = (w) => `<div class="pop" style="width:${w}px"><div class="ph"><span>CASSIE</span><span>×</span></div><div class="chips"><span data-m="0">Explain</span><span data-m="1">Answer</span><span data-m="2">Code</span></div><div class="ty" style="min-height:60px"></div></div>`;

  // INTRO -------------------------------------------------------------------
  S('intro1', 'intro', (r) => {
    const k = kin(r, ['Every', 'night,', 'there’s', 'something', 'new', 'to', 'learn.'], [0, 4]);
    const ic = ['book', 'pencil', 'flask'].map((n) => icon(n, r, 46));
    return { update(lt) { kinUpdate(k, lt, 0.2, 0.2); ic.forEach((n, i) => { n.style.left = 720 + i * 52 + 'px'; n.style.top = 170 + (i % 2) * 16 + 'px'; popIn(n, lt, 1.4 + i * 0.12); }); } };
  });
  S('intro2', 'intro', (r) => {
    const k = kin(r, ['47', 'slides.', 'One', 'exam.', 'And', 'it’s', '2', 'AM.'], [6, 7]);
    const c = icon('clock', r, 64);
    return { update(lt) { kinUpdate(k, lt, 0.3, 0.3); c.style.left = '468px'; c.style.top = '140px'; popIn(c, lt, 2.4, 0.4, `rotate(${Math.sin(lt * 18) * 8 * span(lt, 2.6, 3.2)}deg)`); } };
  });

  // PROBLEM -----------------------------------------------------------------
  S('prob1', 'problem', (r) => {
    const cards = collageCards(r);
    const k = kin(r, ['You', 'just', 'want', 'it', 'to', 'make', 'sense.'], [5, 6]); k.style.fontSize = '50px';
    return { update(lt) {
      kinUpdate(k, lt, 0.25, 0.14);
      cards.forEach((c, i) => {
        const a = i / cards.length * Math.PI * 2 + lt * 0.25, kk = out3(span(lt, 0.1 + i * 0.05, 0.8 + i * 0.05));
        c.style.left = 500 + Math.cos(a) * 400 * lerp(1.6, 1, kk) - c.offsetWidth / 2 + 'px'; c.style.top = 300 + Math.sin(a) * 230 * lerp(1.6, 1, kk) - c.offsetHeight / 2 + 'px';
        c.style.opacity = kk; c.style.transform = `rotate(${Math.sin(i * 1.7) * 10}deg)`; c.style.filter = `blur(${(1 - kk) * 8}px)`;
      });
    } };
  });
  S('prob2', 'problem', (r, s) => {
    const cards = collageCards(r);
    const k = kin(r, ['But', 'it’s', 'buried', 'in', 'tabs,', 'PDFs,', '&', 'slides.'], [2]); k.style.fontSize = '44px'; k.style.padding = '0 250px';
    return { update(lt) {
      kinUpdate(k, lt, 0.3, 0.3);
      cards.forEach((c, i) => {
        const a = i / cards.length * Math.PI * 2 + 0.6 + lt * 0.8, rr = lerp(1.05, 0.92, ease(span(lt, 0, s.d)));
        c.style.left = 500 + Math.cos(a) * 360 * rr - c.offsetWidth / 2 + 'px'; c.style.top = 300 + Math.sin(a) * 210 * rr - c.offsetHeight / 2 + 'px';
        c.style.opacity = 1; c.style.filter = 'none'; c.style.transform = `rotate(${Math.sin(i * 1.7 + lt * 2) * 14}deg)`;
      });
    } };
  });
  S('simple', 'problem', (r) => {
    const xs = [130, 300, 380, 560, 700, 780];
    const letters = 'Simple'.split('').map((c) => make(`<div class="letter">${c}</div>`, r));
    const whole = make(`<div class="letter" style="left:0;right:0;text-align:center;top:205px;color:#d8343c">Simple.</div>`, r);
    const guides = [];
    [140, 235, 330, 410].forEach((y) => guides.push(make(`<div class="guide" style="left:0;right:0;height:1.5px;top:${y}px"></div>`, r)));
    xs.forEach((x) => guides.push(make(`<div class="guide" style="top:0;bottom:0;width:1.5px;left:${x}px"></div>`, r)));
    return { update(lt) {
      const close = ease(span(lt, 1.2, 1.8));
      letters.forEach((n, i) => {
        n.style.left = lerp(xs[i], [300, 420, 470, 610, 720, 770][i], close) + 'px'; n.style.top = '205px';
        const k = span(lt, 0.05 + i * 0.07, 0.3 + i * 0.07); n.style.opacity = k * (1 - span(lt, 1.6, 1.8)); n.style.filter = `blur(${(1 - k) * 12}px)`;
      });
      whole.style.opacity = span(lt, 1.65, 1.85);
      guides.forEach((g, i) => { g.style.opacity = span(lt, i * 0.03, 0.3 + i * 0.03) * (1 - close); });
    } };
  });
  S('logo', 'red', (r) => {
    const word = make(`<div style="position:absolute;left:300px;top:230px;font:850 92px Inter;letter-spacing:-.05em;color:#16131c"><span style="position:relative;display:inline-block;padding:0 6px"><i class="sel" style="position:absolute;inset:6px 0 4px;background:#ffe066;border-radius:10px;transform-origin:left;z-index:-1"></i>Cassie</span></div>`, r);
    const sub = make(`<div style="position:absolute;left:0;right:0;top:370px;text-align:center;font:600 30px Inter;color:#4a4650">the study buddy that lives where you study</div>`, r);
    const cur = make(`<div style="position:absolute">${CUR(40)}</div>`, r);
    return { update(lt) {
      const k = span(lt, 0.2, 0.5); word.style.opacity = k; word.style.filter = `blur(${(1 - k) * 10}px)`;
      const sw = ease(span(lt, 0.5, 1.1)); $('.sel', word).style.transform = `scaleX(${sw})`;
      cur.style.opacity = span(lt, 0.4, 0.5) * (1 - span(lt, 1.6, 1.8)); cur.style.left = lerp(300, 610, sw) + 'px'; cur.style.top = '330px';
      sub.style.opacity = span(lt, said('logo', 'a study') , said('logo', 'a study') + 0.3);
    }, cast(lt) { const [x, y] = W(780, 250); return [{ id: 'logo', outfit: 'classic', mood: 'happy', x, y, s: 0.6 * back(span(lt, 1.2, 1.6)), shadow: false }]; } };
  });

  // FEATURES ----------------------------------------------------------------
  S('highlight', 'red', (r) => {
    r.style.background = 'linear-gradient(180deg,#efe7dc,#e4d9c9)';
    const zoom = make(`<div style="position:absolute;inset:0;transform-origin:420px 250px"></div>`, r);
    const mon = make(`<div class="monitor" style="left:240px;top:60px;width:520px;height:440px"><div class="scr" style="left:0;top:0;width:520px;height:320px;padding:10px"><div style="background:#fff;width:100%;height:100%;border-radius:4px;overflow:hidden;position:relative">${ART}</div></div><div class="stand" style="left:225px;top:320px;width:70px;height:90px"></div><div class="stand" style="left:170px;top:405px;width:180px;height:12px;border-radius:6px"></div></div>`, zoom);
    const pop = make(POPHTML(330), zoom); Object.assign(pop.style, { left: '300px', top: '250px', transformOrigin: 'left top' });
    const cur = make(`<div style="position:absolute">${CUR(26)}</div>`, zoom);
    const OUT = [
      'It’s the cell’s <b>recycling loop</b> — it breaks acetyl-CoA down and charges up <b>NADH & FADH₂</b>.',
      '<b>CO₂, NADH, FADH₂</b> (and a little ATP).',
      '<span style="font-family:monospace;color:#9fe2bf">krebs = ["CO2", "NADH", "FADH2"]</span>',
    ];
    const tE = said('highlight', 'explains'), tA = said('highlight', 'answers'), tC = said('highlight', 'code');
    return { update(lt) {
      const z = ease(span(lt, 0.3, 1.2)); zoom.style.transform = `scale(${lerp(1, 1.32, z)}) translate(${lerp(0, -20, z)}px, ${lerp(0, 30, z)}px)`;
      const drag = ease(span(lt, 1.0, 1.9)); $('.mk i', mon).style.transform = `scaleX(${drag})`;
      cur.style.left = lerp(270, 470, drag) + 'px'; cur.style.top = lerp(218, 240, drag) + 'px'; cur.style.opacity = span(lt, 0.9, 1.0) * (1 - span(lt, tE - 0.2, tE));
      pop.style.opacity = span(lt, tE - 0.3, tE - 0.1); pop.style.transform = `translateY(${(1 - back(span(lt, tE - 0.3, tE + 0.1))) * 20}px) scale(.62)`;
      const m = lt < tA ? 0 : lt < tC ? 1 : 2, from = [tE, tA, tC][m];
      pop.querySelectorAll('[data-m]').forEach((c) => c.classList.toggle('on', +c.dataset.m === m));
      typeInto($('.ty', pop), OUT[m], span(lt, from, from + 1.1));
    } };
  }, 'Highlight anything');
  S('followup', 'red', (r) => {
    r.style.background = 'linear-gradient(180deg,#f3ede6,#ebe2d6)';
    const pop = make(`<div class="pop" style="left:200px;top:70px;width:600px;font-size:22px"><div class="ph"><span>CASSIE</span><span>×</span></div><div style="opacity:.85">It’s the cell’s <b>recycling loop</b> — it breaks acetyl-CoA down and charges up <b>NADH & FADH₂</b>.</div>
      <div class="q" style="margin-top:14px;display:flex;gap:8px"><div class="in" style="flex:1;background:rgba(255,255,255,.1);border-radius:12px;padding:12px 14px;font:500 20px Inter;color:#fff"></div><span style="background:#f6f2ec;color:#16131c;border-radius:12px;padding:12px 16px;font:800 18px Inter">Ask</span></div>
      <div class="a2" style="margin-top:12px;color:#d9d4dd;font-size:20px"></div></div>`, r);
    const hint = chip('💡 Hint', r, false, 24); Object.assign(hint.style, { left: '200px', top: '470px' });
    const hintBox = make(`<div style="position:absolute;left:340px;top:452px;width:460px;background:#fff8d6;border-radius:16px;padding:14px 18px;font:600 20px/1.4 Inter;color:#4a3b00;box-shadow:0 10px 24px rgba(0,0,0,.08)">Hint: where do the electrons go next? 🤔</div>`, r);
    const tF = said('followup', 'follow'), tH = said('followup', 'hint');
    return { update(lt) {
      pop.style.opacity = span(lt, 0, 0.2);
      typeInto($('.in', pop), 'why does it need oxygen?', span(lt, tF - 0.3, tF + 0.6));
      typeInto($('.a2', pop), 'Oxygen catches the used electrons at the end of the chain — no oxygen, the cycle backs up and stops.', span(lt, tF + 0.8, tH));
      popIn(hint, lt, tH - 0.2);
      const pr = span(lt, tH + 0.1, tH + 0.25); hint.style.transform = `scale(${back(span(lt, tH - 0.2, tH + 0.1)) * (1 - 0.08 * Math.sin(pr * Math.PI))})`;
      hintBox.style.opacity = span(lt, tH + 0.3, tH + 0.5); hintBox.style.transform = `translateY(${(1 - out3(span(lt, tH + 0.3, tH + 0.7))) * 16}px)`;
    } };
  }, 'Follow-ups & hints');
  S('snip', 'red', (r) => {
    r.style.background = '#f7f5f1';
    const page = make(`<div style="position:absolute;left:40px;top:70px;width:560px;height:480px;background:#fff;border-radius:14px;box-shadow:0 10px 30px rgba(0,0,0,.08);padding:20px"><div style="font:800 22px Inter">Linear functions</div><div style="font:15px Inter;color:#666;margin:6px 0 10px">Plot the line through (0, 1) and (2, 5).</div><svg viewBox="0 0 300 200" width="420" height="280" style="margin-left:40px"><path d="M30 10V190M10 170H290" stroke="#bbb" stroke-width="2"/><path d="M40 182 L270 22" stroke="#16131c" stroke-width="3"/><circle cx="80" cy="154" r="5" fill="#16131c"/><circle cx="160" cy="98" r="5" fill="#16131c"/></svg></div>`, r);
    const snip = make(`<div style="position:absolute;border:3px dashed #d8343c;border-radius:6px;background:rgba(216,52,60,.06)"></div>`, r);
    const board = make(`<div style="position:absolute;top:60px;width:380px;height:500px;background:#fff;border-radius:18px;box-shadow:0 20px 50px rgba(0,0,0,.18);padding:16px;overflow:hidden"><b style="font:800 18px Inter">Your snip</b><div style="font:15px/1.5 Inter;margin:10px 0"><b>Graph of y = 2x + 1</b><ol style="margin:4px 0 0;padding-left:18px"><li class="st">Start at (0, 1).</li><li class="st">Slope 2: up 2, right 1.</li><li class="st">Plot (2, 5) and join the dots.</li></ol></div><svg viewBox="0 0 300 200" width="348" height="232"><rect width="300" height="200" fill="#fafafa"/><path d="M30 10V190M10 170H290" stroke="#ccc" stroke-width="2"/><path d="M40 182 L270 22" stroke="#999" stroke-width="2"/></svg></div>`, r);
    const cur = make(`<div style="position:absolute">${CUR(26)}</div>`, r);
    const tB = said('snip', 'board');
    return { update(lt) {
      const d = ease(span(lt, 0.4, 1.6));
      Object.assign(snip.style, { left: '85px', top: '150px', width: lerp(10, 440, d) + 'px', height: lerp(10, 300, d) + 'px', opacity: span(lt, 0.35, 0.45) * (1 - span(lt, tB, tB + 0.2)) });
      cur.style.left = 85 + lerp(10, 440, d) + 'px'; cur.style.top = 150 + lerp(10, 300, d) + 'px'; cur.style.opacity = span(lt, 0.3, 0.4) * (1 - span(lt, 1.8, 2.0));
      const sl = out3(span(lt, tB - 0.3, tB + 0.3)); board.style.left = lerp(1000, 590, sl) + 'px';
      board.querySelectorAll('.st').forEach((x, i) => { x.style.opacity = span(lt, tB + 0.6 + i * 0.45, tB + 0.8 + i * 0.45); });
    } };
  }, 'Snip any picture');
  S('board', 'red', (r) => {
    r.style.background = '#f4f1ec';
    const b = make(`<div style="position:absolute;left:150px;top:50px;width:700px;height:510px;background:#fff;border-radius:18px;box-shadow:0 20px 50px rgba(0,0,0,.14);padding:16px;overflow:hidden"><div style="display:flex;justify-content:space-between;align-items:center"><b style="font:800 20px Inter">Cassie’s board</b><span class="chk" style="font:800 16px Inter;background:#16131c;color:#fff;padding:9px 14px;border-radius:999px">✓ Check my work</span></div>
      <div style="display:flex;gap:8px;margin:12px 0">${['✏️', '🖍️', '📏', 'T', '🧽'].map((x) => `<i style="width:40px;height:40px;border-radius:10px;border:1px solid #e3e0da;display:grid;place-items:center;font-style:normal;font-size:18px">${x}</i>`).join('')}<i style="width:22px;height:22px;border-radius:50%;background:#d8343c;margin:9px 0 0 10px"></i><i style="width:22px;height:22px;border-radius:50%;background:#3b7fe0;margin:9px 0 0"></i></div>
      <div class="shot" style="position:absolute;left:30px;top:120px;width:640px;height:300px;background:#fafafa;border-radius:10px;overflow:hidden;box-shadow:inset 0 0 0 1px #eee"><div style="padding:16px 20px;font:700 22px Inter">Find the area of the triangle.</div><svg viewBox="0 0 640 240" width="640" height="240"><path d="M120 200 L420 200 L270 40 Z" fill="#eef3ff" stroke="#16131c" stroke-width="3"/><text x="260" y="226" font-size="20" font-weight="700">10 cm</text><path class="ink" d="M270 40 L270 200" stroke="#d8343c" stroke-width="5" stroke-dasharray="6 0" fill="none"/><text class="ink2" x="282" y="130" font-size="24" fill="#d8343c" font-weight="800">h = 6</text><text class="ink3" x="440" y="120" font-size="26" fill="#d8343c" font-weight="800">A = ½·10·6 = 30</text></svg></div>
      <div class="ok" style="position:absolute;left:30px;right:30px;bottom:18px;background:#e8f8ef;color:#167a45;font:800 19px Inter;padding:12px 14px;border-radius:12px">Correct — 30 cm². Nice use of the height ✓</div></div>`, r);
    const key = make(`<div style="position:absolute;left:400px;top:250px;display:flex;gap:10px"><span style="font:800 30px Inter;background:#16131c;color:#fff;padding:14px 20px;border-radius:14px">Ctrl</span><span style="font:800 30px Inter;background:#16131c;color:#fff;padding:14px 22px;border-radius:14px">V</span></div>`, r);
    const tP = said('board', 'paste'), tC = said('board', 'check');
    return { update(lt) {
      b.style.opacity = span(lt, 0, 0.2);
      key.style.opacity = span(lt, tP - 0.4, tP - 0.2) * (1 - span(lt, tP + 0.3, tP + 0.5)); key.style.transform = `scale(${back(span(lt, tP - 0.4, tP))})`;
      $('.shot', b).style.opacity = span(lt, tP + 0.2, tP + 0.4);
      const ink = span(lt, 0.2, tP - 0.2);
      $('.ink', b).style.opacity = span(lt, tP + 0.4, tP + 0.5); $('.ink2', b).style.opacity = span(lt, tP + 0.6, tP + 0.7); $('.ink3', b).style.opacity = span(lt, tP + 0.9, tP + 1.0);
      const pr = span(lt, tC + 0.1, tC + 0.25); $('.chk', b).style.transform = `scale(${1 - 0.1 * Math.sin(pr * Math.PI)})`;
      $('.ok', b).style.opacity = span(lt, tC + 0.3, tC + 0.5); void ink;
    } };
  }, 'Draw, paste & check');
  S('files', 'maroon', (r) => {
    r.style.background = 'linear-gradient(135deg,#f6efe8,#efe3ea)';
    const F = [['PDF', '#e5484d', 'Anatomy.pdf'], ['PPT', '#e8702a', 'Module 6.pptx'], ['DOC', '#2b579a', 'Notes.docx'], ['IMG', '#2fae74', 'photo.jpg']];
    const files = F.map(([t, c, n]) => make(`<div style="position:absolute;width:150px;height:186px;background:#fff;border-radius:16px;box-shadow:0 14px 30px rgba(0,0,0,.12);padding:14px"><span style="display:inline-block;background:${c};color:#fff;font:900 18px Inter;padding:5px 10px;border-radius:8px">${t}</span><div style="font:700 14px Inter;margin-top:10px">${n}</div>${'<div style="height:9px;background:#eee;border-radius:5px;margin-top:9px"></div>'.repeat(4)}</div>`, r));
    const reader = make(`<div style="position:absolute;left:330px;top:140px;width:340px;height:320px;background:#16131c;border-radius:22px;color:#fff;padding:22px;box-shadow:0 24px 50px rgba(0,0,0,.3)"><div style="font:800 13px Inter;letter-spacing:.18em;color:#b9b5bd">CASSIE IS READING</div><div class="pg" style="font:800 30px Inter;margin:12px 0">page 1 of 412</div><div style="height:10px;background:rgba(255,255,255,.15);border-radius:6px"><i class="bar" style="display:block;height:100%;background:#f2a7b5;border-radius:6px;width:0"></i></div><div style="display:flex;gap:10px;margin-top:18px">${['🫀', '🧬', '📈'].map((e) => `<span class="dg" style="flex:1;height:90px;border-radius:12px;background:rgba(255,255,255,.08);display:grid;place-items:center;font-size:40px">${e}</span>`).join('')}</div><div style="font:600 15px Inter;color:#cfcad4;margin-top:12px">diagrams included</div></div>`, r);
    const tD = said('files', 'drop'), tR = said('files', 'reads');
    return { update(lt) {
      files.forEach((f, i) => {
        const at = tD + i * 0.55, fly = ease(span(lt, at + 0.6, at + 1.3));
        const sx = [40, 810, 40, 810][i], sy = [60, 60, 340, 340][i];
        f.style.left = lerp(sx, 425, fly) + 'px'; f.style.top = lerp(sy, 210, fly) + 'px';
        f.style.opacity = span(lt, at, at + 0.2) * (1 - span(lt, at + 1.1, at + 1.3)); f.style.transform = `scale(${back(span(lt, at, at + 0.35)) * lerp(1, 0.4, fly)}) rotate(${lerp((i % 2 ? 8 : -8), 0, fly)}deg)`;
      });
      reader.style.opacity = span(lt, tD + 0.7, tD + 0.9);
      const p = ease(span(lt, tR - 0.6, tR + 1.6)); $('.pg', reader).textContent = `page ${Math.max(1, Math.round(p * 412))} of 412`; $('.bar', reader).style.width = p * 100 + '%';
      reader.querySelectorAll('.dg').forEach((g, i) => { g.style.opacity = span(lt, tR + 0.6 + i * 0.25, tR + 0.8 + i * 0.25); });
    } };
  }, 'PDFs, slides, docs & photos');
  S('reviewer', 'maroon', (r) => {
    r.style.background = 'linear-gradient(135deg,#f6efe8,#efe3ea)';
    const ph = make(`<div class="phone" style="left:300px;top:40px;width:270px;height:540px"><div class="in"><div style="height:46px;display:grid;place-items:center;font:800 15px Inter;border-bottom:1px solid #e5e0d8">Cassie</div>
      <div class="bub u m1" style="top:62px;font-size:14px">Make me a reviewer 📝</div>
      <div class="bub a m2" style="top:118px;font-size:13px;max-width:82%"><b>Reviewer — Anatomy</b><br><b>Key terms</b><br>• <b>Tissue</b> — cells working together<br>• <b>Organ</b> — tissues with one job<br>• <b>System</b> — organs as a team<br><b>Practice</b><br>1. What links organs into systems?</div>
      <div class="m3" style="position:absolute;left:14px;right:14px;top:360px;background:#fff;border-radius:14px;box-shadow:0 8px 20px rgba(0,0,0,.1);padding:10px;display:flex;align-items:center;gap:10px"><div style="width:34px;height:42px;border-radius:7px;background:#2b579a;color:#fff;font:900 14px Inter;display:grid;place-items:center">W</div><div style="font:700 12px Inter;flex:1">Reviewer – Anatomy.docx<div style="font:500 11px Inter;color:#888">Word file · ready</div></div><div style="background:#16131c;color:#fff;font:800 11px Inter;padding:7px 10px;border-radius:999px">Download</div></div></div></div>`, r);
    const fm = ['Word', 'PDF', 'Image', 'Text'].map((f, i) => chip(f, r, i === 0, 22));
    const tS = said('reviewer', 'save');
    return { update(lt) {
      ph.style.transform = `perspective(1200px) rotateY(${lerp(-24, -6, out3(span(lt, 0, 1.2)))}deg) rotateX(4deg)`;
      $('.m1', ph).style.opacity = span(lt, 0.2, 0.4);
      $('.m2', ph).style.opacity = span(lt, 0.8, 1.0); $('.m2', ph).style.clipPath = `inset(0 0 ${(1 - span(lt, 0.8, 2.0)) * 100}% 0)`;
      $('.m3', ph).style.opacity = span(lt, said('reviewer', 'makes'), said('reviewer', 'makes') + 0.2); $('.m3', ph).style.transform = `scale(${back(span(lt, said('reviewer', 'makes'), said('reviewer', 'makes') + 0.4))})`;
      fm.forEach((c, i) => { c.style.left = '640px'; c.style.top = 140 + i * 80 + 'px'; popIn(c, lt, tS + 0.25 + i * 0.3); });
    } };
  }, 'Reviewers you can save');
  S('graphs', 'red', (r) => {
    r.style.background = '#fbfaf7';
    const b = make(`<div style="position:absolute;left:170px;top:50px;width:660px;height:510px;background:#fff;border-radius:18px;box-shadow:0 20px 50px rgba(0,0,0,.12);padding:16px 20px"><div style="font:800 13px Inter;letter-spacing:.12em;color:#999">CASSIE’S BOARD</div><div style="font:800 26px Inter;margin:4px 0 6px">y = x² − 5x + 6</div>
      <svg viewBox="0 0 400 260" width="620" height="400"><g stroke="#eee">${Array.from({ length: 9 }, (_, i) => `<path d="M${40 + i * 40} 10V250"/>`).join('')}${Array.from({ length: 7 }, (_, i) => `<path d="M10 ${10 + i * 40}H390"/>`).join('')}</g><path d="M80 10V250M10 210H390" stroke="#999" stroke-width="2"/>
      <path class="par" d="${(() => { let d = ''; for (let i = 0; i <= 60; i++) { const x = -0.5 + i * 6.5 / 60, y = x * x - 5 * x + 6; d += (i ? 'L' : 'M') + (80 + x * 40).toFixed(1) + ' ' + (210 - y * 20).toFixed(1); } return d; })()}" fill="none" stroke="#d8343c" stroke-width="4" stroke-dasharray="900" stroke-dashoffset="900"/>
      <g class="pts"><circle cx="160" cy="210" r="7" fill="#16131c"/><circle cx="200" cy="210" r="7" fill="#16131c"/><circle cx="180" cy="215" r="6" fill="#3b7fe0"/><text x="140" y="240" font-size="15" font-weight="700">x=2</text><text x="196" y="240" font-size="15" font-weight="700">x=3</text></g></svg></div>`, r);
    return { update(lt) {
      b.style.opacity = span(lt, 0, 0.25); b.style.transform = `translateY(${(1 - out3(span(lt, 0, 0.5))) * 50}px)`;
      $('.par', b).setAttribute('stroke-dashoffset', String(900 * (1 - ease(span(lt, 0.6, 2.2)))));
      $('.pts', b).style.opacity = span(lt, 2.2, 2.4);
    } };
  }, 'Real graphs');
  S('image', 'green', (r) => {
    r.style.background = 'linear-gradient(135deg,#eef7f1,#f3f0f8)';
    const u = make(`<div class="bub u" style="top:70px;right:60px;font-size:21px">generate an image of a plant cell</div>`, r);
    const pic = make(`<div style="position:absolute;left:250px;top:140px;width:500px;height:400px;background:#fff;border-radius:20px;box-shadow:0 20px 50px rgba(0,0,0,.14);padding:14px"><div style="font:600 17px Inter;margin-bottom:10px">Here’s your picture of a plant cell 🌱</div>
      <svg viewBox="0 0 470 300" width="470" height="300" class="cell"><rect x="20" y="20" width="430" height="260" rx="34" fill="#d8f3dc" stroke="#2d6a4f" stroke-width="8"/><rect x="34" y="34" width="402" height="232" rx="26" fill="#ecfbe9" stroke="#74c69d" stroke-width="3"/><circle cx="235" cy="150" r="52" fill="#b5838d" stroke="#6d597a" stroke-width="5"/><circle cx="246" cy="140" r="16" fill="#6d597a"/>${[[110, 90], [360, 95], [120, 210], [350, 205], [300, 60], [170, 245]].map(([x, y]) => `<ellipse cx="${x}" cy="${y}" rx="30" ry="15" fill="#52b788" stroke="#2d6a4f" stroke-width="3"/>`).join('')}<path d="M70 150 q30 -40 60 0 t60 0" stroke="#95d5b2" stroke-width="5" fill="none"/></svg>
      <div style="position:absolute;right:16px;bottom:14px;background:#16131c;color:#fff;font:800 14px Inter;padding:8px 13px;border-radius:999px">Download image</div></div>`, r);
    const dots = make(`<div style="position:absolute;left:470px;top:300px;font:900 40px Inter;color:#9a9aa3">• • •</div>`, r);
    return { update(lt) {
      typeInto(u, 'generate an image of a plant cell', span(lt, 0.1, 1.0)); u.style.opacity = span(lt, 0.05, 0.15);
      dots.style.opacity = span(lt, 1.1, 1.2) * (1 - span(lt, 1.6, 1.7));
      const k = span(lt, 1.7, 2.3); pic.style.opacity = k; pic.style.filter = `blur(${(1 - k) * 14}px)`; pic.style.transform = `scale(${lerp(0.94, 1, out3(k))})`;
    } };
  }, 'Generate an image');
  S('quiz', 'navy', (r) => {
    r.style.background = 'linear-gradient(135deg,#eef2ff,#f6f2ff)';
    const q = make(`<div style="position:absolute;left:170px;top:60px;width:660px"><div class="lbl">QUESTION 3 OF 10</div><div style="font:800 32px Inter;margin:8px 0 18px;letter-spacing:-.02em">What does the Krebs cycle make?</div>${['Glucose', 'Oxygen', 'NADH & FADH₂', 'Chlorophyll'].map((o, i) => `<div class="op" style="display:flex;align-items:center;gap:12px;background:#fff;border-radius:14px;padding:13px 16px;margin-bottom:10px;font:650 21px Inter;box-shadow:0 6px 16px rgba(0,0,0,.06)"><b style="width:30px;height:30px;border-radius:50%;background:#eee;display:grid;place-items:center;font-size:15px">${'ABCD'[i]}</b>${o}</div>`).join('')}<div class="ok" style="font:800 22px Inter;color:#167a45">Correct! 🎉 Next question →</div></div>`, r);
    return { update(lt) {
      q.style.opacity = span(lt, 0, 0.2);
      const pick = said('quiz', 'one at a');
      q.querySelectorAll('.op').forEach((o, i) => { const sel = i === 2 && lt > pick; o.style.background = sel ? '#e8f8ef' : '#fff'; o.style.boxShadow = sel ? '0 0 0 3px #3fbf7f' : '0 6px 16px rgba(0,0,0,.06)'; o.style.opacity = span(lt, 0.15 + i * 0.12, 0.35 + i * 0.12); });
      $('.ok', q).style.opacity = span(lt, pick + 0.15, pick + 0.3);
    } };
  }, 'Quiz me');
  S('research', 'maroon', (r) => {
    r.style.background = 'linear-gradient(135deg,#f7efe9,#f1e6e9)';
    const P = [['Mitochondrial ATP production in human cells', 'Smith, J., Lee, K., et al.', '2021', 'Cell Metabolism'], ['The citric acid cycle revisited', 'Garcia, M. & Chen, L.', '2019', 'Nature Reviews'], ['Energy pathways in exercise physiology', 'Okafor, A.', '2023', 'Journal of Physiology']];
    const cards = P.map(([ti, au, y, v]) => make(`<div class="card2" style="left:60px;width:600px;padding:14px 18px"><div style="font:800 19px Inter">${ti}</div><div style="font:500 15px Inter;color:#6f6a76;margin-top:4px">${au} (${y}) · <i>${v}</i></div><div style="display:flex;gap:8px;margin-top:8px"><span style="font:700 12px Inter;background:#f1edf7;padding:4px 9px;border-radius:999px">cited 1.2k</span><span style="font:700 12px Inter;background:#f1edf7;padding:4px 9px;border-radius:999px">open access</span></div></div>`, r));
    const styles = ['APA', 'MLA', 'IEEE', 'Chicago'].map((x) => chip(x, r, false, 24));
    const T = ['a p a', 'm l a', 'triple', 'chicago'].map((w) => said('research', w));
    return { update(lt) {
      cards.forEach((c, i) => { c.style.top = 60 + i * 150 + 'px'; c.style.opacity = span(lt, 0.3 + i * 0.35, 0.5 + i * 0.35); c.style.transform = `translateX(${(1 - out3(span(lt, 0.3 + i * 0.35, 0.8 + i * 0.35))) * -50}px)`; });
      styles.forEach((c, i) => { c.style.left = '730px'; c.style.top = 110 + i * 92 + 'px'; popIn(c, lt, T[i] - 0.1); const on = lt >= T[i] && (i === 3 || lt < T[i + 1]); c.style.background = on ? '#16131c' : '#fff'; c.style.color = on ? '#fff' : '#16131c'; });
    } };
  }, 'Research with real sources');
  S('web', 'navy', (r) => {
    r.style.background = 'linear-gradient(135deg,#eef4ff,#f4f0fb)';
    const u = make(`<div class="bub u" style="top:60px;right:60px;font-size:20px">What’s new in the 2026 science curriculum?</div>`, r);
    const a = make(`<div class="bub a" style="top:140px;left:60px;max-width:620px;font-size:19px">Here’s what changed this year, checked against live sources: more hands-on labs, a new data-literacy unit, and climate science across grades.</div>`, r);
    const src = ['🔎 deped.gov.ph', '📰 rappler.com', '🌐 unesco.org'].map((x) => chip(x, r, false, 19));
    const live = make(`<div style="position:absolute;left:60px;top:470px;font:800 18px Inter;color:#167a45;display:flex;gap:8px;align-items:center"><i style="width:12px;height:12px;border-radius:50%;background:#2fbf71;box-shadow:0 0 0 6px rgba(47,191,113,.2)"></i>checked just now</div>`, r);
    return { update(lt) {
      u.style.opacity = span(lt, 0.05, 0.2); a.style.opacity = span(lt, 0.6, 0.8);
      src.forEach((c, i) => { c.style.left = 60 + i * 230 + 'px'; c.style.top = '330px'; popIn(c, lt, 1.2 + i * 0.25); });
      live.style.opacity = span(lt, 2.2, 2.4);
    } };
  }, 'Web — live sources');
  S('talk', 'pink', (r) => {
    r.style.background = 'linear-gradient(135deg,#fff1ee,#fde6ea)';
    const tk = chip('❤️ Talk', r, true, 24); Object.assign(tk.style, { left: '60px', top: '70px' });
    const u = make(`<div class="bub u" style="top:150px;right:60px;font-size:21px">honestly I feel so behind 😩</div>`, r);
    const a = make(`<div class="bub a" style="top:240px;left:60px;max-width:640px;font-size:20px">That’s a lot to carry. You’re not behind forever — you’re behind <i>today</i>. Let’s pick one thing, do 25 minutes, then breathe. And yes — sleep counts as studying.</div>`, r);
    return { update(lt) {
      popIn(tk, lt, said('talk', 'tap talk') - 0.2);
      u.style.opacity = span(lt, said('talk', 'she listens') - 0.4, said('talk', 'she listens') - 0.2);
      a.style.opacity = span(lt, said('talk', 'honest') - 0.4, said('talk', 'honest') - 0.2); a.style.transform = `translateY(${(1 - out3(span(lt, said('talk', 'honest') - 0.4, said('talk', 'honest')))) * 16}px)`;
    } };
  }, 'Talk');
  S('memory', 'pink', (r) => {
    r.style.background = 'linear-gradient(135deg,#fff5f2,#f6eefc)';
    const panel = make(`<div style="position:absolute;left:220px;top:60px;width:560px;background:#fff;border-radius:20px;box-shadow:0 20px 50px rgba(0,0,0,.12);padding:22px 26px"><div style="font:800 13px Inter;letter-spacing:.16em;color:#999">WHAT CASSIE REMEMBERS</div>
      ${[['📚', 'Topics', 'Biology · Chemistry · Algebra'], ['🎯', 'Weak spots', 'Krebs cycle · factoring'], ['🔥', 'Streak', '5 days in a row'], ['📱', 'Stored', 'only on this device']].map(([e, k, v]) => `<div class="row" style="display:flex;align-items:center;gap:14px;padding:14px 0;border-top:1px solid #f0ece8"><span style="font-size:30px">${e}</span><div><div style="font:800 18px Inter">${k}</div><div style="font:500 17px Inter;color:#6f6a76">${v}</div></div></div>`).join('')}</div>`, r);
    const T = ['topics', 'weak', 'streak', 'device'].map((w) => said('memory', w));
    return { update(lt) { panel.style.opacity = span(lt, 0, 0.2); panel.querySelectorAll('.row').forEach((x, i) => { x.style.opacity = span(lt, T[i] - 0.2, T[i]); x.style.transform = `translateX(${(1 - out3(span(lt, T[i] - 0.2, T[i] + 0.2))) * 30}px)`; }); } };
  }, 'Memory');
  S('timer', 'grey', (r) => {
    r.style.background = 'linear-gradient(135deg,#f2f1f6,#e9e7f0)';
    const ring = make(`<div style="position:absolute;left:350px;top:60px;width:300px;height:300px"><svg viewBox="0 0 200 200" width="300" height="300"><circle cx="100" cy="100" r="86" fill="none" stroke="#e1dde8" stroke-width="14"/><circle class="arc" cx="100" cy="100" r="86" fill="none" stroke="#16131c" stroke-width="14" stroke-linecap="round" transform="rotate(-90 100 100)" stroke-dasharray="540.35"/></svg><div class="tm" style="position:absolute;inset:0;display:grid;place-items:center;font:900 64px Inter;letter-spacing:-.04em"></div></div>`, r);
    const presets = ['25 · 5', '50 · 10', 'your own ✏️'].map((p, i) => chip(p, r, i === 2, 22));
    return { update(lt) {
      const prog = span(lt, 0.3, 2.4), secs = Math.round(lerp(1500, 0, prog));
      $('.tm', ring).textContent = prog >= 1 ? 'Break!' : `${Math.floor(secs / 60)}:${String(secs % 60).padStart(2, '0')}`;
      $('.arc', ring).setAttribute('stroke-dashoffset', String(540.35 * prog)); $('.arc', ring).setAttribute('stroke', prog >= 1 ? '#ee9a8c' : '#16131c');
      presets.forEach((p, i) => { p.style.left = 300 + i * 150 + 'px'; p.style.top = '400px'; popIn(p, lt, said('timer', 'breaks') - 0.2 + i * 0.15); });
    } };
  }, 'Focus timer');
  S('levels', 'grey', (r) => {
    r.style.background = 'linear-gradient(135deg,#f4f2ee,#ece9f2)';
    const seg = make(`<div style="position:absolute;left:80px;top:70px;display:flex;gap:8px">${['Elementary', 'Middle', 'High school', 'College'].map((x) => `<span class="lv" style="font:800 20px Inter;padding:11px 16px;border-radius:999px;background:#fff;box-shadow:0 6px 16px rgba(0,0,0,.06)">${x}</span>`).join('')}</div>`, r);
    const sample = make(`<div style="position:absolute;left:80px;top:160px;width:560px;background:#fff;border-radius:16px;padding:20px 22px;box-shadow:0 10px 24px rgba(0,0,0,.08);color:#2a2730"></div>`, r);
    const ctl = make(`<div style="position:absolute;left:680px;top:170px;width:260px;background:#fff;border-radius:16px;padding:18px;box-shadow:0 10px 24px rgba(0,0,0,.08)"><div style="font:800 13px Inter;letter-spacing:.14em;color:#999">TEXT SIZE</div><div style="display:flex;gap:8px;margin:8px 0 16px">${['A', 'A', 'A'].map((x, i) => `<span class="ts" style="flex:1;text-align:center;font:800 ${16 + i * 6}px Inter;padding:8px 0;border-radius:10px;border:1px solid #e3e0da">${x}</span>`).join('')}</div><div style="display:flex;justify-content:space-between;align-items:center;font:800 17px Inter">Easy reading <i class="tg" style="width:52px;height:30px;border-radius:999px;background:#ddd;position:relative"><b style="position:absolute;top:3px;left:3px;width:24px;height:24px;border-radius:50%;background:#fff;transition:none"></b></i></div></div>`, r);
    const TXT = ['Plants make food from sunlight. 🌞', 'Plants use sunlight to turn water and air into sugar.', 'Photosynthesis converts light energy into glucose in the chloroplasts.', 'Photosynthesis couples the light reactions to the Calvin cycle, fixing CO₂ into G3P.'];
    const tE = said('levels', 'elementary'), tC = said('levels', 'college'), tB = said('levels', 'bigger'), tR = said('levels', 'easier');
    return { update(lt) {
      seg.style.opacity = span(lt, 0, 0.2);
      const lv = lt < tE ? 0 : Math.min(3, Math.floor(lerp(0, 3.99, span(lt, tE, tC + 0.2))));
      seg.querySelectorAll('.lv').forEach((x, i) => { x.style.background = i === lv ? '#16131c' : '#fff'; x.style.color = i === lv ? '#fff' : '#16131c'; });
      const big = lt > tB ? 1 : 0, easy = lt > tR ? 1 : 0;
      sample.textContent = TXT[lv]; sample.style.font = `${big ? 600 : 500} ${big ? 28 : 21}px/${easy ? 1.9 : 1.45} Inter`; sample.style.letterSpacing = easy ? '.02em' : '0';
      sample.style.opacity = span(lt, 0.2, 0.4);
      ctl.style.opacity = span(lt, tB - 0.6, tB - 0.4);
      ctl.querySelectorAll('.ts').forEach((x, i) => { x.style.background = (big ? 2 : 0) === i ? '#16131c' : '#fff'; x.style.color = (big ? 2 : 0) === i ? '#fff' : '#16131c'; });
      $('.tg', ctl).style.background = easy ? '#2fbf71' : '#ddd'; $('.tg b', ctl).style.left = easy ? '25px' : '3px';
    } };
  }, 'Your level, easy to read');
  S('voice', 'navy', (r) => {
    r.style.background = 'linear-gradient(135deg,#eef2ff,#f6f2ff)';
    const mic = make(`<div style="position:absolute;left:120px;top:190px;width:150px;height:150px;border-radius:50%;background:#16131c;display:grid;place-items:center"><svg viewBox="0 0 24 24" width="62" height="62"><path fill="#fff" d="M12 15a3 3 0 0 0 3-3V6a3 3 0 0 0-6 0v6a3 3 0 0 0 3 3zm5-3a5 5 0 0 1-10 0H5a7 7 0 0 0 6 6.9V21h2v-2.1A7 7 0 0 0 19 12h-2z"/></svg></div>`, r);
    const rings = [0, 1, 2].map(() => make(`<div style="position:absolute;left:120px;top:190px;width:150px;height:150px;border-radius:50%;border:4px solid #7fb3ff"></div>`, r));
    const said1 = make(`<div class="bub u" style="top:120px;right:60px;font-size:21px;max-width:560px"></div>`, r);
    const bars = Array.from({ length: 22 }, (_, i) => make(`<i style="position:absolute;bottom:150px;width:12px;border-radius:6px;background:#3b7fe0;left:${380 + i * 22}px"></i>`, r));
    const spk = make(`<div style="position:absolute;left:380px;top:470px;font:800 19px Inter;color:#3b5bdb">🔊 Cassie is reading the answer aloud</div>`, r);
    const tR = said('voice', 'read');
    return { update(lt) {
      rings.forEach((g, i) => { const k = ((lt * 0.9 + i / 3) % 1); g.style.transform = `scale(${1 + k * 0.8})`; g.style.opacity = (1 - k) * (lt < tR ? 1 : 0.3); });
      typeInto(said1, 'what’s the difference between mitosis and meiosis?', span(lt, 0.2, tR - 0.3)); said1.style.opacity = span(lt, 0.15, 0.25);
      bars.forEach((b, i) => { const on = lt > tR - 0.1; b.style.height = (on ? 14 + 50 * Math.abs(Math.sin(lt * 9 + i * 0.7)) * (0.5 + 0.5 * Math.sin(i * 0.4)) : 6) + 'px'; b.style.opacity = on ? 1 : 0.3; });
      spk.style.opacity = span(lt, tR, tR + 0.2);
    } };
  }, 'Voice');
  S('pro', 'grey', (r) => {
    r.style.background = 'linear-gradient(135deg,#f4f2ee,#e7e5ec)';
    const sw = make(`<div style="position:absolute;left:520px;top:140px;display:inline-grid;grid-template-columns:1fr 1fr;padding:6px;border-radius:999px;background:#fff;box-shadow:0 10px 26px rgba(0,0,0,.1)"><i class="th" style="position:absolute;top:6px;bottom:6px;left:6px;width:calc(50% - 6px);border-radius:999px;background:#16131c"></i><span class="a" style="position:relative;font:800 24px Inter;padding:14px 24px">Student</span><span class="b" style="position:relative;font:800 24px Inter;padding:14px 24px">Professional</span></div>`, r);
    const uses = ['✉️ emails', '📊 reports', '🖥️ decks'].map((x) => chip(x, r, false, 22));
    const tP = said('pro', 'professional');
    return { tP, update(lt) {
      const pro = ease(span(lt, tP - 0.1, tP + 0.2));
      $('.th', sw).style.transform = `translateX(${pro * 100}%)`;
      $('.a', sw).style.color = pro < 0.5 ? '#fff' : '#6f6a76'; $('.b', sw).style.color = pro >= 0.5 ? '#fff' : '#6f6a76';
      sw.style.opacity = span(lt, 0, 0.2);
      uses.forEach((c, i) => { c.style.left = 520 + i * 150 + 'px'; c.style.top = '260px'; popIn(c, lt, said('pro', ['emails', 'reports', 'decks'][i]) - 0.1); });
    }, cast(lt) { const [x, y] = W(260, 340); const pro = lt > said('pro', 'suits') - 0.1; return [{ id: pro ? 'pro' : 'stu', outfit: pro ? 'professor' : 'classic', mood: pro ? 'celebratory' : 'happy', x, y, s: 1.0 * (pro ? back(span(lt, said('pro', 'suits') - 0.1, said('pro', 'suits') + 0.3)) : 1 - span(lt, said('pro', 'suits') - 0.25, said('pro', 'suits') - 0.1)) }]; } };
  }, 'Student or Professional');
  S('colour', 'red', (r) => {
    const SW = ['#d8343c', '#3b7fe0', '#2fae74', '#9b5de5'];
    const bg = make(`<div style="position:absolute;inset:0"></div>`, r);
    const app = make(`<div style="position:absolute;left:90px;top:60px;width:440px;height:480px;border-radius:22px;overflow:hidden;box-shadow:0 20px 50px rgba(0,0,0,.18)"><div class="g" style="position:absolute;inset:0"></div><div style="position:relative;padding:14px;font:800 16px Inter;text-align:center;background:rgba(255,255,255,.5);backdrop-filter:blur(8px)">Cassie</div><div class="bub a" style="top:70px;font-size:15px;max-width:75%">Hi! What are we studying today?</div><div class="bub u ub" style="top:150px;font-size:15px">the Krebs cycle 🔁</div><div style="position:absolute;left:14px;right:14px;bottom:14px;height:52px;border-radius:16px;background:rgba(255,255,255,.85)"></div></div>`, r);
    const row = make(`<div style="position:absolute;left:600px;top:200px;display:flex;gap:16px">${SW.map((c) => `<i style="width:66px;height:66px;border-radius:50%;background:${c};box-shadow:0 8px 20px rgba(0,0,0,.15)"></i>`).join('')}</div>`, r);
    const cur = make(`<div style="position:absolute">${CUR(28)}</div>`, r);
    const pick = (lt) => (lt < 0.7 ? 0 : lt < 1.4 ? 1 : lt < 2.1 ? 2 : 3);
    return { update(lt) {
      const c = SW[pick(lt)];
      bg.style.background = `radial-gradient(60% 80% at 75% 60%, ${c}33, transparent 70%), #faf8f5`;
      $('.g', app).style.background = `radial-gradient(70% 60% at 20% 20%, ${c}, transparent 70%), radial-gradient(60% 60% at 90% 90%, ${c}aa, transparent 70%), linear-gradient(160deg, ${c}55, #fbf8f3)`;
      $('.ub', app).style.background = c;
      [...row.children].forEach((n, j) => { n.style.outline = j === pick(lt) ? '4px solid #16131c' : 'none'; n.style.outlineOffset = '4px'; });
      cur.style.left = 600 + pick(lt) * 82 + 40 + 'px'; cur.style.top = '236px';
    } };
  }, 'Your colour');
  S('anywhere', 'green', (r) => {
    r.style.background = 'linear-gradient(135deg,#eef7f1,#f3f0f8)';
    const mon = make(`<div class="monitor" style="left:60px;top:90px;width:420px;height:360px"><div class="scr" style="left:0;top:0;width:420px;height:260px;padding:8px"><div style="background:#f3f3f3;width:100%;height:100%;border-radius:4px;display:flex;position:relative"><div style="flex:1;padding:10px"><div style="height:12px;background:#ddd;border-radius:4px;width:60%"></div>${'<div style="height:7px;background:#e8e8e8;border-radius:4px;margin-top:8px"></div>'.repeat(10)}</div><div class="side" style="width:130px;background:#fff;border-left:1px solid #ddd;padding:8px"><div style="font:800 11px Inter">Cassie</div><div style="display:flex;gap:4px;margin-top:6px">${'<i style="flex:1;height:26px;border:1px solid #ddd;border-radius:6px"></i>'.repeat(3)}</div><div style="height:60px;background:#f6f4f0;border-radius:6px;margin-top:8px"></div></div><i class="tab" style="position:absolute;right:-2px;top:90px;width:16px;height:46px;border-radius:8px 0 0 8px;background:#16131c"></i></div></div><div class="stand" style="left:180px;top:260px;width:60px;height:70px"></div><div class="stand" style="left:130px;top:326px;width:160px;height:10px;border-radius:5px"></div></div>`, r);
    const ph = make(`<div class="phone" style="left:560px;top:110px;width:170px;height:340px;border-radius:32px;padding:8px"><div class="in" style="border-radius:26px;background:linear-gradient(160deg,#fde7e3,#e9e4ff)"><div style="font:800 12px Inter;text-align:center;padding-top:14px">Cassie</div><div style="margin:40px auto 0;width:60px;height:60px;border-radius:16px;background:#fff;display:grid;place-items:center;box-shadow:0 6px 14px rgba(0,0,0,.1)">${CUR(26, '#16131c').replace('position:absolute;', '')}</div><div style="text-align:center;font:700 11px Inter;margin-top:8px">Add to Home Screen</div></div></div>`, r);
    const chips = [['Chrome extension', 'chrome'], ['PDF side panel', 'side panel'], ['phone app', 'phone']].map(([x, w]) => [chip(x, r, false, 20), w]);
    return { update(lt) {
      mon.style.opacity = span(lt, 0, 0.2);
      $('.side', mon).style.opacity = span(lt, said('anywhere', 'side panel') - 0.1, said('anywhere', 'side panel') + 0.1);
      ph.style.opacity = span(lt, said('anywhere', 'phone') - 0.4, said('anywhere', 'phone') - 0.2); ph.style.transform = `perspective(900px) rotateY(${lerp(-30, -10, out3(span(lt, said('anywhere', 'phone') - 0.4, said('anywhere', 'phone') + 0.4)))}deg)`;
      chips.forEach(([c, w], i) => { c.style.left = [60, 320, 580][i] + 'px'; c.style.top = '485px'; popIn(c, lt, said('anywhere', w) - 0.15); });
    } };
  }, 'Anywhere you study');
  S('private', 'green', (r) => {
    r.style.background = 'linear-gradient(135deg,#f3f7f2,#eef0f8)';
    const lock = make(`<div style="position:absolute;left:420px;top:70px;width:160px;height:160px;border-radius:40px;background:#16131c;display:grid;place-items:center;box-shadow:0 20px 40px rgba(0,0,0,.2)"><svg viewBox="0 0 24 24" width="80" height="80"><rect x="5" y="10" width="14" height="11" rx="2" fill="#fff"/><path d="M8 10V7a4 4 0 0 1 8 0v3" stroke="#fff" stroke-width="2" fill="none"/></svg></div>`, r);
    const items = [['Free', 'free'], ['No account', 'no account'], ['Notes stay on your device', 'device']].map(([x, w]) => [chip(x, r, w === 'device', 26), w]);
    return { update(lt) {
      popIn(lock, lt, 0.1, 0.45);
      items.forEach(([c, w], i) => { c.style.left = [370, 490, 335][i] + 'px'; c.style.top = i < 2 ? '290px' : '380px'; popIn(c, lt, said('private', w) - 0.15); });
    } };
  }, 'Private & free');

  // TRY IT --------------------------------------------------------------------
  S('cta1', 'red', (r) => {
    const a = make(`<div style="position:absolute;left:300px;top:200px;font:550 66px Inter;letter-spacing:-.035em">Whatever you’re</div>`, r);
    const b = make(`<div style="position:absolute;left:170px;top:300px;font:550 66px Inter;letter-spacing:-.035em;color:#d8343c">studying,</div>`, r);
    return { update(lt) { [[a, 0.2], [b, 0.8]].forEach(([n, at]) => { const k = span(lt, at, at + 0.4); n.style.opacity = k; n.style.filter = `blur(${(1 - k) * 14}px)`; n.style.transform = `translateX(${(1 - out3(k)) * 40}px)`; }); } };
  });
  S('cta2', 'pink', (r) => {
    const k = kin(r, ['Cassie', 'explains', 'it.'], [0]); k.style.fontSize = '84px';
    return { update(lt) { kinUpdate(k, lt, 0.25, 0.25); } };
  });
  S('cta3', 'red', (r) => {
    const a = make(`<div style="position:absolute;left:90px;top:200px;font:600 68px Inter;letter-spacing:-.04em">Your new</div>`, r);
    const b = make(`<div style="position:absolute;left:560px;top:200px;font:600 68px Inter;letter-spacing:-.04em">study buddy</div>`, r);
    const url = make(`<div style="position:absolute;left:0;right:0;top:380px;text-align:center"><span style="display:inline-block;background:#16131c;color:#fff;font:800 32px Inter;padding:18px 30px;border-radius:999px">Try it free · askcassie.pages.dev</span></div>`, r);
    const tT = said('cta3', 'try');
    return { update(lt) {
      [[a, 0.1], [b, 0.5]].forEach(([n, at]) => { const k = span(lt, at, at + 0.4); n.style.opacity = k; n.style.filter = `blur(${(1 - k) * 14}px)`; });
      url.style.opacity = span(lt, tT - 0.1, tT + 0.1); url.style.transform = `scale(${0.9 + 0.1 * back(span(lt, tT - 0.1, tT + 0.3))})`;
    }, cast(lt) { const [x, y] = W(470, 240); return [{ id: 'buddy', outfit: 'classic', mood: lt > tT ? 'celebratory' : 'happy', x, y, s: 0.6 * back(span(lt, 0.3, 0.7)), shadow: false }]; } };
  });
  // hold the end card a little after the last line
  scenes[scenes.length - 1].t1 += 1.6;
  const TOTAL = scenes[scenes.length - 1].t1;
  window.TOTAL = TOTAL;
  // chapters from the script
  CH = ['intro', 'problem', 'features', 'try'].map((c) => { const xs = window.TL.filter((s) => s.chapter === c); return [xs[0].t0, c === 'try' ? TOTAL : xs[xs.length - 1].t0 + xs[xs.length - 1].dur]; });
  /* ---------------- frame chrome: glow, wave, chapters, ruler ---------------- */
  const glow = $('#glow');
  const blobs = [0, 1, 2, 3, 4].map(() => make('<i></i>', glow));
  const wave = $('#wave'), wg = wave.getContext('2d');
  wave.style.width = '1000px'; wave.style.height = '300px'; wave.style.filter = 'blur(10px)';
  const chs = [...document.querySelectorAll('#chapters div')];
  const ruler = $('#ruler');
  const ticks = Array.from({ length: 60 }, (_, i) => make(`<i class="${i % 5 === 0 ? 'big' : ''}"></i>`, ruler));
  const hexRGB = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
  let palNow = null;
  function chrome(t, s) {
    const target = PAL[s ? s.pal : 'red'].map(hexRGB);
    if (!palNow) palNow = target.map((c) => c.slice());
    palNow = palNow.map((c, i) => c.map((v, j) => v + (target[i][j] - v) * 0.12));
    const rgba = (i, a) => `rgba(${palNow[i].map(Math.round).join(',')},${a})`;
    // glow under the card
    blobs.forEach((b, i) => {
      const x = 230 + i * 220 + Math.sin(t * 0.6 + i) * 70, y = 170 + Math.cos(t * 0.5 + i * 1.7) * 50 + (i % 2) * 90;
      Object.assign(b.style, { left: x - 300 + 'px', top: y - 210 + 'px', width: '600px', height: '420px', background: rgba(i % 3, 1) });
    });
    // soft wave at the bottom of the card
    wg.clearRect(0, 0, 500, 150);
    for (let i = 0; i < 70; i++) {
      const x = i * 7.3, h = 30 + 45 * (0.5 + 0.5 * Math.sin(i * 0.45 + t * 2.2)) * (0.6 + 0.4 * Math.sin(i * 0.13 - t));
      const gr = wg.createLinearGradient(0, 150 - h, 0, 150);
      gr.addColorStop(0, rgba(i % 2 ? 1 : 0, 0)); gr.addColorStop(1, rgba(i % 2 ? 1 : 0, 0.55));
      wg.fillStyle = gr; wg.fillRect(x, 150 - h, 9, h);
    }
    wave.style.opacity = s && s.root.style.background ? 0.35 : 0.9;
    // chapters
    chs.forEach((c, i) => {
      const [a, b] = CH[i], on = t >= a && t < b;
      c.classList.toggle('on', on);
      const st = $('.streak', c);
      st.style.opacity = on ? 1 : 0; st.style.left = `calc(${span(t, a, b) * 100}% - 5px)`;
    });
    ticks.forEach((tk, i) => { tk.style.left = ((i * 24 - t * 60) % 1440 + 1440) % 1440 - 200 + 'px'; });
  }

  /* ---------------- seek ---------------- */
  CassieStage.mount($('#stage'));
  const flash = $('#flash');
  window.seek = function (t) {
    const s = scenes.find((x) => t >= x.t0 && t < x.t1) || scenes[scenes.length - 1];
    scenes.forEach((x) => { const on = x === s; x.root.style.display = on ? 'block' : 'none'; x.tags.forEach((g) => { g.style.display = on ? '' : 'none'; }); });
    const lt = t - s.t0;
    const k = span(lt, 0, 0.32);
    s.root.style.filter = k < 1 ? `blur(${(1 - k) * 16}px)` : 'none';
    s.root.style.transform = `scale(${lerp(1.04, 1, out3(k))})`;
    s.update(lt, s.d);
    s.tags.forEach((g) => { g.style.opacity = span(lt, 0.1, 0.3); });
    flash.style.opacity = (1 - span(lt, 0, 0.12)) * 0.45 * (t > 0.1 ? 1 : 0);
    chrome(t, s);
    CassieStage.set(s.cast ? s.cast(lt) : []);
    CassieStage.frame(t);
  };
  (function wait() { if (CassieStage.isReady()) { window.seek(0); window.READY = true; } else setTimeout(wait, 50); })();
})();
